run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - makezero
    - revive

linters-settings:
  dupl:
    threshold: 150
  exhaustive:
    default-signifies-exhaustive: false
  gocyclo:
    min-complexity: 15
  mnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  govet:
    enable:
      - shadow
  lll:
    line-length: 140
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - dupl
    - path: cmd/
      linters:
        - forbidigo
    - path: internal/ui/
      linters:
        - forbidigo
    - linters:
        - lll
      source: "^//go:generate "
    - text: "ifElseChain"
      linters:
        - gocritic
    - text: "Consider pre-allocating"
      linters:
        - prealloc
    - text: "indent-error-flow"
      linters:
        - revive
    - text: "Magic number"
      linters:
        - mnd
    - text: "unused-parameter"
      linters:
        - revive
    - text: "that stutters"
      linters:
        - revive